# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-06 05:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itsapp', '0002_electronics_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('elec_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Electronics', verbose_name='기기카테고리')),
                ('lang_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Language', verbose_name='언어카테고리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
