# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='elec_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lang_category',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', help_text='최대 140자 입력 가능', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='post', verbose_name='내용'),
        ),
    ]
