# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-06 12:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsapp', '0002_electronics_language'),
        ('post', '0002_auto_20190206_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='elec_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Electronics', verbose_name='기기카테고리'),
        ),
        migrations.AddField(
            model_name='post',
            name='lang_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Language', verbose_name='언어카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='게시물'),
        ),
    ]
