# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-08 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190207_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
    ]
