# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190208_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='elec_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Electronics', verbose_name='기기카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itsapp.Language', verbose_name='언어카테고리'),
        ),
    ]
