# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-09 06:16
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190209_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
